import {
  Plus,
  Sigma,
  List,
  Binary,
  Variable,
  Hash,
  Search,
  Database,
  Trash2,
  ListTree,
  Key,
  Zap,
  CircleDot,
  Filter,
  AlertTriangle,
  Divide,
  Code2,
  FileBox,
  Layers,
  GitMerge,
  Puzzle,
  ListChecks,
  Settings2,
  Equal,
  Braces,
  MoreHorizontal,
  CheckCircle2,
  File,
  FileType,
  Lock,
  Minus,
  Flag,
  Table,
  FileStack,
  Box,
  FilePlus,
  GitCompare,
  Share2,
  HelpCircle,
  ChevronDown,
  RefreshCw,
  FunctionSquare,
  ListOrdered,
  type LucideIcon,
} from "lucide-react";

export const icons: { [key: string]: LucideIcon } = {
  "Add": Plus,
  "Aggregate": Sigma,
  "Aggregate Expression List": List,
  "Aggregation": Sigma,
  "And": Binary,
  "Assign": Variable,
  "At Least One": CheckCircle2,
  "At Most One": CircleDot,
  "Bitmap": Box,
  "Bitmap Merge": GitMerge,
  "Bitmap Probe": Search,
  "Bitmap Scan": Search,
  "Buffer Scan": Search,
  "Building Key": Key,
  "Cache": Zap,
  "Cache Probe": Search,
  "Column": CircleDot,
  "Complicated": AlertTriangle,
  "Data": Database,
  "Delete": Trash2,
  "Dequeue": ListTree,
  "Derivation Logic": Code2,
  "Distinct": Filter,
  "Distinct Hash Table Probe": Search,
  "Distinct Hash Table Scan": Search,
  "Distinct Key Range": Key,
  "Divide": Divide,
  "Dynamic Bitmap": Box,
  "EVI Symbol Probe": Search,
  "EVI Symbol Scan": Search,
  "Encoded Vector Index": FileType,
  "Encoded Vector Index, Parallel": FileType,
  "Enqueue": ListTree,
  "EqualTo": Equal,
  "Expression Object": Braces,
  "Fetch N Rows": Filter,
  "Final Select": ListChecks,
  "Function": FunctionSquare,
  "GreaterThan": MoreHorizontal,
  "GreaterThanOrEqualTo": MoreHorizontal,
  "Group By Expression List": Layers,
  "Hash Grouping": Layers,
  "Hash Join": Plus,
  "Hash Probe": Search,
  "Hash Scan": Search,
  "Host Variable": Variable,
  "If None One": Binary,
  "Index Distinct Probe": Search,
  "Index Distinct Scan": Search,
  "Index Grouping": Layers,
  "Index Object": FileBox,
  "Index Random Input/Output": Settings2,
  "Index Scan - Key Positioning": Key,
  "Index Scan - Key Positioning, Parallel": Key,
  "Index Scan - Key Selection": Key,
  "Index Scan - Key Selection, Parallel": Key,
  "Insert": Plus,
  "Key": Key,
  "Left Exception Join Fanout": GitMerge,
  "Left Join Fanout": GitMerge,
  "LessThan": MoreHorizontal,
  "LessThanOrEqualTo": MoreHorizontal,
  "List Scan": List,
  "Literal": Hash,
  "Lock Row For Update": Lock,
  "Logic": Code2,
  "Merge": GitMerge,
  "Multiply": MoreHorizontal,
  "Nested Loop Join": GitMerge,
  "NotEqualTo": Equal,
  "Object": Puzzle,
  "Or": Binary,
  "Order By Expression List": ListOrdered,
  "Predicate Expression List": Filter,
  "Predicate Logic": Code2,
  "Queue": ListTree,
  "Radix Index Probe": Search,
  "Radix Index Scan": Search,
  "Random Input/Output": RefreshCw,
  "RI Reduction Union": GitMerge,
  "RI Reduction Union 2": GitMerge,
  "Rank": Hash,
  "Relation Object": Puzzle,
  "Row Number List Probe": Search,
  "Row Number List Scan": Search,
  "Scalar Subselect": CircleDot,
  "Scan": Search,
  "Select": ListChecks,
  "Selection Expression List": List,
  "Single Fanout": Share2,
  "Skip Sequential Table Scan": List,
  "Skip Sequential Table Scan, Parallel": List,
  "Sort": ListOrdered,
  "Sorted List Probe": Search,
  "Sorted List Scan": ListOrdered,
  "Special Logic": Code2,
  "Special Register": Key,
  "Subquery Merge": GitMerge,
  "Subtract": Minus,
  "Sync Flag": Flag,
  "Table Object": Table,
  "Table Probe": Search,
  "Table Scan": Search,
  "Table Scan, Parallel": Search,
  "TEMPORARY DISTINCT SORTED LIST": Filter,
  "Temporary Buffer": FileStack,
  "Temporary Distinct Hash Table": FilePlus,
  "Temporary Hash Table": FilePlus,
  "Temporary Index": File,
  "Temporary Indexed List Scan": List,
  "Temporary List": List,
  "Temporary Row Number List": List,
  "Temporary Sorted List": ListOrdered,
  "Temporary Table": FilePlus,
  "Union Merge": GitMerge,
  "Union Switch": GitCompare,
  "Unknown": HelpCircle,
  "Unnest": ChevronDown,
  "Update": RefreshCw,
  "User Defined Table Function": FunctionSquare,
  "VALUES LIST": ListChecks,
};

// Default icon when none is found
export const defaultIcon: LucideIcon = HelpCircle;
