import { expect, test, vi } from 'vitest'
import { generateCrudStatement } from '../../database/crud';
import { TableColumn } from '../../types';

// Names are delimited against the connection of the base extension, which no test has
vi.mock('../../base', () => ({ getInstance: () => undefined }));

function column(name: string, dataType: string, overrides: Partial<TableColumn> = {}): TableColumn {
  return {
    TABLE_SCHEMA: `RMOELLER`,
    TABLE_NAME: `MYTABLE`,
    COLUMN_NAME: name,
    SYSTEM_COLUMN_NAME: name,
    DATA_TYPE: dataType,
    IS_NULLABLE: `N`,
    HAS_DEFAULT: `N`,
    COLUMN_TEXT: ``,
    IS_IDENTITY: `NO`,
    ...overrides
  };
}

/** The table of the review comment: every column is generated, and only C1 is an identity column */
const allGenerated: TableColumn[] = [
  column(`C1`, `INTEGER`, { HAS_DEFAULT: `J`, IS_IDENTITY: `YES`, IS_NULLABLE: `Y` }),
  column(`C2`, `TIMESTAMP`, { HAS_DEFAULT: `E` }),
  column(`C3`, `TIMESTAMP`, { HAS_DEFAULT: `Q` }),
  column(`C3E`, `TIMESTAMP`, { HAS_DEFAULT: `R` }),
  column(`C4`, `TIMESTAMP`, { HAS_DEFAULT: `X` }),
];

test('Generated columns are left out of an INSERT, and every value is a host variable with a bind statement', () => {
  const columns = [
    ...allGenerated,
    column(`NAME`, `VARCHAR`, { CHARACTER_MAXIMUM_LENGTH: 20 }),
    column(`CREATED`, `DATE`, { HAS_DEFAULT: `Y`, COLUMN_DEFAULT: `CURRENT DATE` }),
  ];

  const statement = generateCrudStatement(`INSERT`, `RMOELLER`, `MYTABLE`, columns);

  expect(statement).toBe([
    `-- C1 omitted: identity, generated by default`,
    `-- C2 omitted: row change timestamp, generated always`,
    `-- C3 omitted: row begin`,
    `-- C3E omitted: row end`,
    `-- C4 omitted: transaction start ID`,
    `INSERT INTO RMOELLER.MYTABLE (`,
    `  NAME,`,
    `  CREATED`,
    `)`,
    `VALUES (`,
    `  ?,  -- NAME - VARCHAR(20) NOT NULL`,
    `  ?  -- CREATED - DATE NOT NULL`,
    `);`,
    `bind: '', '2024-01-01';`
  ].join(`\n`));
});

test('A table of nothing but generated columns inserts the defaults', () => {
  const statement = generateCrudStatement(`INSERT`, `RMOELLER`, `MYTABLE`, allGenerated);

  expect(statement).toBe([
    `INSERT INTO RMOELLER.MYTABLE (`,
    `  C1,`,
    `  C2,`,
    `  C3,`,
    `  C3E,`,
    `  C4`,
    `)`,
    `VALUES (`,
    `  DEFAULT, -- C1 - INTEGER - identity, generated by default`,
    `  DEFAULT, -- C2 - TIMESTAMP NOT NULL - row change timestamp, generated always`,
    `  DEFAULT, -- C3 - TIMESTAMP NOT NULL - row begin`,
    `  DEFAULT, -- C3E - TIMESTAMP NOT NULL - row end`,
    `  DEFAULT -- C4 - TIMESTAMP NOT NULL - transaction start ID`,
    `);`
  ].join(`\n`));
});

test('The HAS_DEFAULT code is read case sensitively', () => {
  const columns = [
    column(`ROWID`, `CHAR`, { HAS_DEFAULT: `D`, CHARACTER_MAXIMUM_LENGTH: 40 }),
    column(`OPERATION`, `CHAR`, { HAS_DEFAULT: `d`, CHARACTER_MAXIMUM_LENGTH: 1 }),
    column(`NAME`, `VARCHAR`, { CHARACTER_MAXIMUM_LENGTH: 20 }),
  ];

  const statement = generateCrudStatement(`INSERT`, `RMOELLER`, `MYTABLE`, columns);

  expect(statement).toContain(`-- ROWID omitted: ROWID, generated by default`);
  expect(statement).toContain(`-- OPERATION omitted: generated expression using DATA CHANGE OPERATION`);
});

test('An unknown HAS_DEFAULT code is still treated as generated', () => {
  const columns = [
    column(`C1`, `INTEGER`, { HAS_DEFAULT: `Z` }),
    column(`NAME`, `VARCHAR`, { CHARACTER_MAXIMUM_LENGTH: 20 }),
  ];

  expect(generateCrudStatement(`INSERT`, `RMOELLER`, `MYTABLE`, columns)).toContain(`-- C1 omitted: generated value`);
});

test('An identity column is left out when HAS_DEFAULT says nothing', () => {
  const columns = [
    column(`C1`, `INTEGER`, { HAS_DEFAULT: `N`, IS_IDENTITY: `YES` }),
    column(`NAME`, `VARCHAR`, { CHARACTER_MAXIMUM_LENGTH: 20 }),
  ];

  expect(generateCrudStatement(`INSERT`, `RMOELLER`, `MYTABLE`, columns)).toContain(`-- C1 omitted: identity`);
});

test('Generated columns are left out of the SET list of an UPDATE, which assigns host variables', () => {
  const columns = [
    ...allGenerated,
    column(`NAME`, `VARCHAR`, { CHARACTER_MAXIMUM_LENGTH: 20 }),
  ];

  const statement = generateCrudStatement(`UPDATE`, `RMOELLER`, `MYTABLE`, columns, [`C1`]);

  expect(statement).toBe([
    `-- C2 omitted: row change timestamp, generated always`,
    `-- C3 omitted: row begin`,
    `-- C3E omitted: row end`,
    `-- C4 omitted: transaction start ID`,
    `UPDATE RMOELLER.MYTABLE`,
    `SET`,
    `  NAME = ?  -- NAME - VARCHAR(20) NOT NULL`,
    `WHERE`,
    `  C1 = ?  -- C1 - INTEGER`,
    `;`,
    `bind: '', 0;`
  ].join(`\n`));
});

test('A DELETE keeps generated columns in the WHERE clause', () => {
  const statement = generateCrudStatement(`DELETE`, `RMOELLER`, `MYTABLE`, allGenerated, [`C1`]);

  expect(statement).toBe([
    `DELETE FROM RMOELLER.MYTABLE`,
    `WHERE`,
    `  C1 = ?  -- C1 - INTEGER`,
    `;`,
    `bind: 0;`
  ].join(`\n`));
});

test('Without a key, an UPDATE/DELETE uses every column in the WHERE clause, joined with AND, and warns about it', () => {
  const columns = [
    column(`C1`, `INTEGER`),
    column(`C2`, `VARCHAR`, { CHARACTER_MAXIMUM_LENGTH: 10 }),
  ];

  const statement = generateCrudStatement(`DELETE`, `RMOELLER`, `MYTABLE`, columns);

  expect(statement).toBe([
    `-- No primary or unique key found so every column is listed to identify the row. Adjust as needed.`,
    `DELETE FROM RMOELLER.MYTABLE`,
    `WHERE`,
    `  C1 = ?  -- C1 - INTEGER NOT NULL`,
    `  AND C2 = ?  -- C2 - VARCHAR(10) NOT NULL`,
    `;`,
    `bind: 0, '';`
  ].join(`\n`));
});
