
import { TableColumn } from "../types";
import Statement from "./statement";

export type CrudType = `INSERT` | `UPDATE` | `DELETE`;

/**
 * Generates an INSERT, UPDATE or DELETE statement for a table. Every value is a `:name` named
 * host variable, described in a trailing comment, so the statement is valid SQL once those
 * variables are declared or bound.
 * @param schema Schema name, as it comes from the catalog
 * @param name Table name, as it comes from the catalog
 * @param columns All columns of the table, in ordinal position order
 * @param keyColumns Names of the columns which identify a row. Ignored for INSERT
 */
export function generateCrudStatement(type: CrudType, schema: string, name: string, columns: TableColumn[], keyColumns: string[] = []): string {
  switch (type) {
    case `INSERT`: return generateInsert(schema, name, columns);
    case `UPDATE`: return generateUpdate(schema, name, columns, keyColumns);
    case `DELETE`: return generateDelete(schema, name, columns, keyColumns);
  }
}

function generateInsert(schema: string, name: string, columns: TableColumn[]): string {
  const generatedColumns = columns.filter(column => generatedKind(column));
  const insertColumns = columns.filter(column => !generatedKind(column));

  // Every column can be generated, in which case the only way to insert a row is to ask for the defaults
  if (insertColumns.length === 0) {
    return [
      `INSERT INTO ${qualify(schema, name)} (`,
      ...columnList(columns),
      `)`,
      `VALUES (`,
      ...columns.map((column, index) => `  DEFAULT${index < columns.length - 1 ? `,` : ``} -- ${describe(column)} - ${generatedKind(column)}`),
      `);`
    ].join(`\n`);
  }

  const values = valuesList(insertColumns, new Set());

  return [
    ...omissionWarnings(generatedColumns),
    `INSERT INTO ${qualify(schema, name)} (`,
    ...columnList(insertColumns),
    `)`,
    `VALUES (`,
    ...values.lines,
    `);`
  ].join(`\n`);
}

function generateUpdate(schema: string, name: string, columns: TableColumn[], keyColumns: string[]): string {
  const generatedColumns = columns.filter(column => generatedKind(column) && !isKeyColumn(column, keyColumns));
  const setColumns = columns.filter(column => !generatedKind(column) && !isKeyColumn(column, keyColumns));

  if (setColumns.length === 0) {
    throw new Error(`No columns available to update in ${qualify(schema, name)}`);
  }

  // Shared across SET and WHERE so a column used in both places doesn't collide with itself,
  // and so two columns that sanitize to the same host variable name don't collide either.
  const usedNames = new Set<string>();
  const set = setList(setColumns, usedNames);
  const where = whereClause(schema, name, columns, keyColumns, usedNames);

  return [
    ...omissionWarnings(generatedColumns),
    ...where.warnings,
    `UPDATE ${qualify(schema, name)}`,
    `SET`,
    ...set.lines,
    `WHERE`,
    ...where.lines,
    `;`
  ].join(`\n`);
}

function generateDelete(schema: string, name: string, columns: TableColumn[], keyColumns: string[]): string {
  const where = whereClause(schema, name, columns, keyColumns, new Set());

  return [
    ...where.warnings,
    `DELETE FROM ${qualify(schema, name)}`,
    `WHERE`,
    ...where.lines,
    `;`
  ].join(`\n`);
}

function whereClause(schema: string, name: string, columns: TableColumn[], keyColumns: string[], usedNames: Set<string>) {
  // Without a key, every column is listed so the statement never matches more rows than intended
  const predicateColumns = keyColumns.length ? columns.filter(column => isKeyColumn(column, keyColumns)) : columns;

  if (predicateColumns.length === 0) {
    throw new Error(`No columns available to identify a row in ${qualify(schema, name)}`);
  }

  const predicate = wherePredicates(predicateColumns, usedNames);

  return {
    warnings: keyColumns.length ? [] : [`-- No primary or unique key found so every column is listed to identify the row. Adjust as needed.`],
    lines: predicate.lines
  };
}

function isKeyColumn(column: TableColumn, keyColumns: string[]) {
  return keyColumns.includes(column.COLUMN_NAME);
}

/**
 * The HAS_DEFAULT codes from SYSCOLUMNS2
 */
const GENERATED_KINDS: Record<string, string> = {
  'A': `ROWID, generated always`,
  'D': `ROWID, generated by default`,
  'E': `row change timestamp, generated always`,
  'F': `row change timestamp, generated by default`,
  'I': `identity, generated always`,
  'J': `identity, generated by default`,
  'Q': `row begin`,
  'R': `row end`,
  'X': `transaction start ID`,
  'a': `generated expression using a special register`,
  'c': `generated expression using a global variable`,
  'd': `generated expression using DATA CHANGE OPERATION`,
};

/**
 * Get generated type
 */
function generatedKind(column: TableColumn): string | undefined {
  const code = (column.HAS_DEFAULT || ``).trim();

  if (code && code !== `Y` && code !== `N`) {
    return GENERATED_KINDS[code] || `generated value`;
  }

  // Nothing in HAS_DEFAULT to go by, so fall back on the identity flag
  return column.IS_IDENTITY === `YES` ? `identity` : undefined;
}

function omissionWarnings(generatedColumns: TableColumn[]): string[] {
  return generatedColumns.map(column => `-- ${Statement.delimName(column.COLUMN_NAME)} omitted: ${generatedKind(column)}`);
}

function columnList(columns: TableColumn[], indent = `  `): string[] {
  return columns.map((column, index) => `${indent}${Statement.delimName(column.COLUMN_NAME)}${index < columns.length - 1 ? `,` : ``}`);
}

function qualify(schema: string, name: string) {
  return `${Statement.delimName(schema)}.${Statement.delimName(name)}`;
}

/**
 * A valid, unquoted identifier to use as a `:name` host variable for a column. Column names from
 * the catalog can contain characters (quotes, spaces, punctuation) that aren't valid in an
 * identifier, so those are stripped out. `usedNames` avoids collisions when that stripping makes
 * two columns resolve to the same name within one statement.
 */
function hostVariableName(column: TableColumn, usedNames: Set<string>): string {
  const stripped = column.COLUMN_NAME.replace(/[^A-Za-z0-9_]/g, ``);
  const base = !stripped || /^[0-9]/.test(stripped) ? `C${stripped}` : stripped;

  let candidate = base;
  for (let suffix = 2; usedNames.has(candidate); suffix++) {
    candidate = `${base}${suffix}`;
  }

  usedNames.add(candidate);
  return candidate;
}

/** A `:name` host variable per column for a VALUES list, e.g. ":NAME,  -- COL - VARCHAR(20)" */
function valuesList(columns: TableColumn[], usedNames: Set<string>): { lines: string[] } {
  return {
    lines: columns.map((column, index) => `  :${hostVariableName(column, usedNames)}${index < columns.length - 1 ? `,` : ``}  -- ${describe(column)}`)
  };
}

/** A `:name` host variable assignment per column for a SET list, e.g. "COL = :NAME,  -- COL - VARCHAR(20)" */
function setList(columns: TableColumn[], usedNames: Set<string>): { lines: string[] } {
  return {
    lines: columns.map((column, index) => `  ${Statement.delimName(column.COLUMN_NAME)} = :${hostVariableName(column, usedNames)}${index < columns.length - 1 ? `,` : ``}  -- ${describe(column)}`)
  };
}

/** A `:name` host variable predicate per column for a WHERE clause, joined with AND */
function wherePredicates(columns: TableColumn[], usedNames: Set<string>): { lines: string[] } {
  return {
    lines: columns.map((column, index) => `  ${index > 0 ? `AND ` : ``}${Statement.delimName(column.COLUMN_NAME)} = :${hostVariableName(column, usedNames)}  -- ${describe(column)}`)
  };
}

function describe(column: TableColumn): string {
  const type = column.DATA_TYPE.toUpperCase();
  const parts = [Statement.delimName(column.COLUMN_NAME), type];

  if (column.CHARACTER_MAXIMUM_LENGTH) {
    parts[1] += `(${column.CHARACTER_MAXIMUM_LENGTH})`;
  } else if (column.NUMERIC_PRECISION && [`DECIMAL`, `NUMERIC`, `DECFLOAT`, `FLOAT`].includes(type)) {
    parts[1] += `(${column.NUMERIC_PRECISION}${column.NUMERIC_SCALE ? `, ${column.NUMERIC_SCALE}` : ``})`;
  }

  if (column.IS_NULLABLE === `N`) parts[1] += ` NOT NULL`;
  if (column.COLUMN_TEXT && column.COLUMN_TEXT.trim()) parts.push(column.COLUMN_TEXT.trim());

  return parts.join(` - `);
}
